version: '3'

services:
  web:
    build: ./app
    container_name: ques_app
    ports:
      - 8080:8080
    volumes: 
      - ../:/work
    depends_on: 
      - db
    tty: true
    environment:
      - TZ=Asia/Tokyo

  db:
    build: ./db
    container_name: ques_db
    ports:
      - 3308:3306
    environment: 
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalog
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
